In [ ]:
#   NUMPY LAB ASSIGNMENT:-1

In [3]:
#Ques:1 


import numpy as np

my_list = [1,2,3,4,5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


In [5]:
#Ques:2 Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result.

import numpy as np

my_list = [1, 2, 3, 4, 5]
array = np.array(my_list)

print("Array:")
print(array)

print("First element:", array[0])
print("Last element:", array[-1])

multiplied_array = array * 2
print("Array after multiplying each element by 2:")
print(multiplied_array)


Array:
[1 2 3 4 5]
First element: 1
Last element: 5
Array after multiplying each element by 2:
[ 2  4  6  8 10]


In [7]:
#Ques:3 Working with Numpy using Jupyter.
   # part(1) Write a Numpy program to create

import numpy as np

zeros_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = np.full(10, 5)

print("Array of 10 zeros:")
print(zeros_array)
print("\nArray of 10 ones:")
print(ones_array)
print("\nArray of 10 fives:")
print(fives_array)

Array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]
